version: '2'
services:
  rest:
    image: platformnexus/simple-proxy-rest-receiver:0.1
    environment:
      HEALTH_CONFIG_ENABLED: 'false'
      SPRING_APPLICATION_NAME: notification_service
      SPRING_CLOUD_CONFIG_PASSWORD:
      SPRING_CLOUD_CONFIG_URL:
      SPRING_CLOUD_CONFIG_USERNAME:
      SPRING_PROFILES_ACTIVE: insurance,rest_receiver
    volumes:
    - /opt/insurance-receiver/logs:/opt/notification-service/logs
    - /opt/insurance-receiver/conf:/opt/notification-service/conf
    links:
    - redis:redis
    - mysql:mysql
    labels:
      io.rancher.scheduler.affinity:host_label: rest_receiver=true
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name





